name: Rust CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - release-001

jobs:
  check:
    name: Format, Clippy, Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo builds
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt --check
        run: cargo fmt --all -- --check

      - name: cargo clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: cargo check (all targets)
        run: cargo check --all-targets --all-features


